### ISSUE TITLE
Clarification on launch file arguments

### ISSUE THREAD

**Issue by Ekanshh** [DavidPL1/franka_ros_mujoco#5]
First, thanks for the amazing work on this repo! :100: 

I was reviewing the  [`panda.launch`](https://github.com/ubi-agni/franka_ros_mujoco/blob/noetic-devel/launch/panda.launch) file setup and have a couple of questions regarding it:

1. **Xacro vs. MuJoCo XML**:  
   I noticed in the launch file that both a xacro-based scene file (`scene_xml`) and a MuJoCo XML file (`modelfile`) are used, depending on the `use_xacro` argument.  
   - What is the use case for using xacro versus native MuJoCo XML?  
   - When should each approach be preferred?

2. **`use_sim_time`**:  
   Could you explain the purpose of the `use_sim_time` parameter and how it affects the simulation?

Thanks! :rocket:

**Comment by DavidPL1** [comment]
The intended difference between `scene_xml` and `modelfile` was that `scene_xml` was used to create a model with xacro and could be provided as string instead of a file.
Since the way VFS worked was changed in MuJoCo, loading from strings with resources got tricky, so I opted to dump the created model into a file and load that instead (hence `xml_outpath` got introduced).

1. Native MuJoCo requires one explicit file per simulation setup. E.g., the default scene in this package requires two separate files to simulate the robot on the floor and on the table. With xacro, you are more flexible either by introducing bools (i.e. `on_table`) or by configuring the exact position within a launchfile.
Say you want to perform some domain randomization by randomizing the robot position, this can easily done with a single xacro configuration and a single launchfile, while native MuJoCo XML would require either multiple models or messing with the position after loading, which can lead to instabilities.

So in short: if you know your simulation scene will always stay the same use plain MuJoCo XML. If you want more flexibility use xacro.

2. That's actually a ROS-wide parameter, it configures if the system time should be used (use_sim_time=False) or if the time should be published by a component with Clock messages. This mainly affects how timers work and allows running simulations slower or faster than real time while the components operate like in real time.
Generally, if you simulate something you should always use sim time. If your PC is unable to perform a simulation step in real time, you'll lose time in between steps and physics updates and e.g. controller steps will become unstable.
Initially there was a setup where the simulation was being run combined with a real time robotic system and it was required to use system time to keep in sync. I'm not sure this use case still exists, so maybe I'll just make it true by default.

Hope this answers your questions.

**Comment by Ekanshh** [comment]
Thank you, @DavidPL1, for the clarification. :) I am now closing this issue.
